import Head from "next/head";
import Nav from "../components/user/Nav";
import Script from "next/script";
import Link from "next/dist/client/link";
import { useRouter } from "next/router";
import kode from "./user/[kode]";

export default function Home() {
  const seris = [
    { seri: "01", nama: "Fossil" },
    { seri: "02", nama: "G-Shock" },
    { seri: "03", nama: "Casio" },
  ];
  const router = useRouter();
  const sendParamRouter = (seri) => {
    router.push(`/user/${seri}`);
  };
  return (
    <div className={"container"}>
      <Nav />
      <Head>
        <title>Aplikasi Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello Next</h1>
        <h3>Daftar Jam Tangan</h3>
        <ul>
          {jam.map((jam, idx) => (
            <>
              <li key={idx}>
                <Link href={`/user/${jam.seri}`}>
                  <a> {jam.seri}</a>
                </Link>
                <p>{jam.nama}</p>
                <button className="btn btn-primary" onClick={(e) => sendParamRouter(jam.seri)}>
                  Cek Jumlah
                </button>
              </li>
            </>
          ))}
        </ul>
      </main>

      <footer>
        <h4>Footer</h4>
      </footer>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></Script>
    </div>
  );
}
